name: auto-release

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - id: release
        uses: release-drafter/release-drafter@v5
        with:
          publish: true
          prerelease: false
          config-name: auto-release.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}

  build:
    runs-on: ubuntu-latest
    needs:
      - publish
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: npm install
      - run: npm run pkg
      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ needs.publish.outputs.upload_url }}
          asset_path: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
